console.log("---------------------------------- Step 1 -----------------------------------------------");
var myFullName;
myFullName = "Abhishek More";
console.log("Full Name : ",myFullName);
myFullName = "Abhishek Ravindra More";
console.log("Full Name : ",myFullName);
console.log("---------------------------------- Step 2 -----------------------------------------------");
var myLove;
myLove = "I Love Only JS";
console.log(myLove);
console.log("---------------------------------- Step 3 -----------------------------------------------");
var firstName = "Abhishek";
console.log("First Name : ",firstName);
var lastName = "More";
console.log("Last Name : ",lastName);
var age = "26";
console.log("Age : ",age);
var address = "Karvenagar, Pune";
console.log("Address : ",address);
var pincode = "411052";
console.log("Pincode : ", pincode);
var gender = "Male";
console.log("Gender : ", gender);
var isMarried = "No";
console.log("Is Married : ", isMarried);